import { Question, Subject, Level } from "./types";

/**
 * 11+ Exam Question Database - Tiffin & Sutton Grammar Schools
 * Aligned with UK 11+ entrance exam standards
 * Subjects: English, Maths, Science, Reasoning
 * Levels: Foundation, Intermediate, Advanced, Expert
 */

const questionsDatabase: Record<Subject, Record<Level, Question[]>> = {
  english: {
    foundation: [
      {
        id: "eng-f-1",
        subject: "english",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Which word is spelled correctly?",
        options: ["occassion", "occasion", "ocasion", "ocassion"],
        correctAnswer: "occasion",
        explanation: "The correct spelling is 'occasion' with two c's and one s.",
      },
      {
        id: "eng-f-2",
        subject: "english",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Choose the opposite of 'brave':",
        options: ["courageous", "fearless", "timid", "bold"],
        correctAnswer: "timid",
        explanation: "'Timid' means shy or lacking courage.",
      },
      {
        id: "eng-f-3",
        subject: "english",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Which sentence is correct?",
        options: ["She have gone", "She has gone", "She are going", "She do go"],
        correctAnswer: "She has gone",
        explanation: "With 'she', use 'has' not 'have'.",
      },
      {
        id: "eng-f-4",
        subject: "english",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What does 'meticulous' mean?",
        options: ["careless", "very careful", "quick", "lazy"],
        correctAnswer: "very careful",
        explanation: "'Meticulous' means very careful and precise.",
      },
      {
        id: "eng-f-5",
        subject: "english",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Complete: 'The weather was so _____ that we stayed indoors.'",
        options: ["beautiful", "dreadful", "sunny", "mild"],
        correctAnswer: "dreadful",
        explanation: "Bad weather would make us stay indoors.",
      },
    ],
    intermediate: [
      {
        id: "eng-i-1",
        subject: "english",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Which is an example of alliteration?",
        options: ["The quick brown fox", "The silent night", "She sells seashells", "The dark forest"],
        correctAnswer: "She sells seashells",
        explanation: "Alliteration repeats the same beginning sound - 's' in this case.",
      },
      {
        id: "eng-i-2",
        subject: "english",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What does 'pragmatic' mean?",
        options: ["theoretical", "practical", "emotional", "complicated"],
        correctAnswer: "practical",
        explanation: "'Pragmatic' means dealing with things in a practical way.",
      },
      {
        id: "eng-i-3",
        subject: "english",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Which uses subjunctive mood correctly?",
        options: ["If I was you", "If I were you", "If I am you", "If I had been you"],
        correctAnswer: "If I were you",
        explanation: "In subjunctive mood, use 'were' not 'was'.",
      },
      {
        id: "eng-i-4",
        subject: "english",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What does 'ambiguous' mean?",
        options: ["clear", "having multiple meanings", "wrong", "simple"],
        correctAnswer: "having multiple meanings",
        explanation: "'Ambiguous' means it can be understood in more than one way.",
      },
      {
        id: "eng-i-5",
        subject: "english",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Which is similar to 'tenacious'?",
        options: ["weak", "persistent", "lazy", "forgetful"],
        correctAnswer: "persistent",
        explanation: "'Tenacious' means holding firmly or determined.",
      },
    ],
    advanced: [
      {
        id: "eng-a-1",
        subject: "english",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is the purpose of a metaphor?",
        options: ["confuse", "compare using like/as", "create vivid images", "slow narrative"],
        correctAnswer: "create vivid images",
        explanation: "Metaphor compares unlike things directly to create vivid images.",
      },
      {
        id: "eng-a-2",
        subject: "english",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 'juxtaposition'?",
        options: ["contrasting side by side", "repeating words", "exaggeration", "rhyme scheme"],
        correctAnswer: "contrasting side by side",
        explanation: "Juxtaposition places contrasting elements together.",
      },
      {
        id: "eng-a-3",
        subject: "english",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What does 'obfuscate' mean?",
        options: ["clarify", "make unclear", "celebrate", "investigate"],
        correctAnswer: "make unclear",
        explanation: "'Obfuscate' means to deliberately make unclear.",
      },
      {
        id: "eng-a-4",
        subject: "english",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Which demonstrates irony?",
        options: ["The sun is bright", "She was so happy she cried", "He ran fast", "It was interesting"],
        correctAnswer: "She was so happy she cried",
        explanation: "Irony uses language that signifies the opposite.",
      },
      {
        id: "eng-a-5",
        subject: "english",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Effect of short, punchy sentences?",
        options: ["slow pace", "speed up pace", "confuse", "lengthen text"],
        correctAnswer: "speed up pace",
        explanation: "Short sentences create faster pace and urgency.",
      },
    ],
    expert: [
      {
        id: "eng-e-1",
        subject: "english",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What device is 'The silence was deafening'?",
        options: ["Oxymoron", "Metaphor", "Personification", "Hyperbole"],
        correctAnswer: "Oxymoron",
        explanation: "Oxymoron combines contradictory terms.",
      },
      {
        id: "eng-e-2",
        subject: "english",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Significance of unreliable narrator?",
        options: ["confuse", "challenge assumptions", "simplify", "avoid grammar"],
        correctAnswer: "challenge assumptions",
        explanation: "Unreliable narrators force readers to question what they're told.",
      },
      {
        id: "eng-e-3",
        subject: "english",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 'pathos'?",
        options: ["sympathy/pity", "path", "disease", "pattern"],
        correctAnswer: "sympathy/pity",
        explanation: "'Pathos' evokes pity or sympathy.",
      },
      {
        id: "eng-e-4",
        subject: "english",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Function of denouement?",
        options: ["introduce conflict", "resolve plot", "create suspense", "introduce characters"],
        correctAnswer: "resolve plot",
        explanation: "Denouement resolves the plot and ties up loose ends.",
      },
      {
        id: "eng-e-5",
        subject: "english",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is paronomasia?",
        options: ["alliteration", "assonance", "consonance", "pun"],
        correctAnswer: "pun",
        explanation: "Paronomasia uses words with similar sounds but different meanings.",
      },
    ],
  },

  maths: {
    foundation: [
      {
        id: "math-f-1",
        subject: "maths",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 15 + 23?",
        options: ["36", "37", "38", "39"],
        correctAnswer: "38",
        explanation: "15 + 23 = 38.",
      },
      {
        id: "math-f-2",
        subject: "maths",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 50 - 17?",
        options: ["32", "33", "34", "35"],
        correctAnswer: "33",
        explanation: "50 - 17 = 33.",
      },
      {
        id: "math-f-3",
        subject: "maths",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 6 × 7?",
        options: ["40", "41", "42", "43"],
        correctAnswer: "42",
        explanation: "6 × 7 = 42.",
      },
      {
        id: "math-f-4",
        subject: "maths",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 48 ÷ 6?",
        options: ["7", "8", "9", "10"],
        correctAnswer: "8",
        explanation: "48 ÷ 6 = 8.",
      },
      {
        id: "math-f-5",
        subject: "maths",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What fraction is 3 out of 4 parts?",
        options: ["1/4", "2/4", "3/4", "4/4"],
        correctAnswer: "3/4",
        explanation: "3 out of 4 parts is 3/4.",
      },
    ],
    intermediate: [
      {
        id: "math-i-1",
        subject: "maths",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 23 × 4?",
        options: ["88", "90", "92", "94"],
        correctAnswer: "92",
        explanation: "23 × 4 = 92.",
      },
      {
        id: "math-i-2",
        subject: "maths",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 144 ÷ 12?",
        options: ["10", "11", "12", "13"],
        correctAnswer: "12",
        explanation: "144 ÷ 12 = 12.",
      },
      {
        id: "math-i-3",
        subject: "maths",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 3/4 + 1/4?",
        options: ["3/8", "4/8", "1", "5/4"],
        correctAnswer: "1",
        explanation: "3/4 + 1/4 = 4/4 = 1.",
      },
      {
        id: "math-i-4",
        subject: "maths",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Rectangle: length 8cm, width 5cm. Area?",
        options: ["13 cm²", "26 cm²", "40 cm²", "80 cm²"],
        correctAnswer: "40 cm²",
        explanation: "Area = 8 × 5 = 40 cm².",
      },
      {
        id: "math-i-5",
        subject: "maths",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 25% of 80?",
        options: ["15", "20", "25", "30"],
        correctAnswer: "20",
        explanation: "25% of 80 = 80 ÷ 4 = 20.",
      },
    ],
    advanced: [
      {
        id: "math-a-1",
        subject: "maths",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 156 × 23?",
        options: ["3588", "3600", "3650", "3700"],
        correctAnswer: "3588",
        explanation: "156 × 23 = 3588.",
      },
      {
        id: "math-a-2",
        subject: "maths",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 5/6 - 1/3?",
        options: ["1/2", "1/3", "2/3", "1/6"],
        correctAnswer: "1/2",
        explanation: "5/6 - 2/6 = 3/6 = 1/2.",
      },
      {
        id: "math-a-3",
        subject: "maths",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Triangle angles: 45° and 65°. Third angle?",
        options: ["60°", "70°", "80°", "90°"],
        correctAnswer: "70°",
        explanation: "180° - 45° - 65° = 70°.",
      },
      {
        id: "math-a-4",
        subject: "maths",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "If x + 5 = 12, what is x?",
        options: ["5", "6", "7", "8"],
        correctAnswer: "7",
        explanation: "x = 12 - 5 = 7.",
      },
      {
        id: "math-a-5",
        subject: "maths",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 30% of 150?",
        options: ["40", "45", "50", "55"],
        correctAnswer: "45",
        explanation: "30% of 150 = 45.",
      },
    ],
    expert: [
      {
        id: "math-e-1",
        subject: "maths",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is (2³ × 3²) ÷ 6?",
        options: ["10", "12", "14", "16"],
        correctAnswer: "12",
        explanation: "(8 × 9) ÷ 6 = 72 ÷ 6 = 12.",
      },
      {
        id: "math-e-2",
        subject: "maths",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What is 2/3 × 3/4 × 4/5?",
        options: ["1/5", "2/5", "3/5", "4/5"],
        correctAnswer: "2/5",
        explanation: "Cancel common factors: 2/5.",
      },
      {
        id: "math-e-3",
        subject: "maths",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "20% discount on £50 item. Final price?",
        options: ["£35", "£40", "£45", "£48"],
        correctAnswer: "£40",
        explanation: "£50 - £10 = £40.",
      },
      {
        id: "math-e-4",
        subject: "maths",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "If 3x - 5 = 16, what is x?",
        options: ["5", "6", "7", "8"],
        correctAnswer: "7",
        explanation: "3x = 21, so x = 7.",
      },
      {
        id: "math-e-5",
        subject: "maths",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Circle radius 5cm. Area? (π ≈ 3.14)",
        options: ["78.5 cm²", "80 cm²", "85 cm²", "90 cm²"],
        correctAnswer: "78.5 cm²",
        explanation: "πr² = 3.14 × 25 = 78.5 cm².",
      },
    ],
  },

  science: {
    foundation: [
      {
        id: "sci-f-1",
        subject: "science",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Which is a living organism?",
        options: ["Rock", "Tree", "Water", "Soil"],
        correctAnswer: "Tree",
        explanation: "A tree is alive - it grows and reproduces.",
      },
      {
        id: "sci-f-2",
        subject: "science",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Three states of matter?",
        options: ["Solid, liquid, gas", "Solid, water, air", "Hard, soft, liquid", "Solid, liquid, steam"],
        correctAnswer: "Solid, liquid, gas",
        explanation: "The three states are solid, liquid, and gas.",
      },
      {
        id: "sci-f-3",
        subject: "science",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What do plants need to grow?",
        options: ["Only water", "Water, sunlight, nutrients", "Only sunlight", "Only nutrients"],
        correctAnswer: "Water, sunlight, nutrients",
        explanation: "Plants need all three to survive.",
      },
      {
        id: "sci-f-4",
        subject: "science",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Which animal is a mammal?",
        options: ["Fish", "Bird", "Dog", "Frog"],
        correctAnswer: "Dog",
        explanation: "Dogs are mammals with fur and warm blood.",
      },
      {
        id: "sci-f-5",
        subject: "science",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "How plants make food?",
        options: ["Respiration", "Photosynthesis", "Digestion", "Fermentation"],
        correctAnswer: "Photosynthesis",
        explanation: "Photosynthesis uses sunlight to make food.",
      },
    ],
    intermediate: [
      {
        id: "sci-i-1",
        subject: "science",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Frog life cycle?",
        options: ["Egg → Tadpole → Froglet → Adult", "Egg → Adult", "Tadpole → Froglet → Adult", "Egg → Froglet → Adult"],
        correctAnswer: "Egg → Tadpole → Froglet → Adult",
        explanation: "Frogs undergo complete metamorphosis.",
      },
      {
        id: "sci-i-2",
        subject: "science",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Renewable energy source?",
        options: ["Coal", "Oil", "Solar power", "Natural gas"],
        correctAnswer: "Solar power",
        explanation: "Solar power is renewable - the sun keeps providing it.",
      },
      {
        id: "sci-i-3",
        subject: "science",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Function of skeleton?",
        options: ["Produce blood", "Support and protect", "Digest food", "Think"],
        correctAnswer: "Support and protect",
        explanation: "Skeleton supports the body and protects organs.",
      },
      {
        id: "sci-i-4",
        subject: "science",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Water liquid to gas?",
        options: ["Freezing", "Melting", "Evaporation", "Condensation"],
        correctAnswer: "Evaporation",
        explanation: "Evaporation turns water into steam.",
      },
      {
        id: "sci-i-5",
        subject: "science",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Organ that pumps blood?",
        options: ["Brain", "Lungs", "Heart", "Liver"],
        correctAnswer: "Heart",
        explanation: "The heart pumps blood around the body.",
      },
    ],
    advanced: [
      {
        id: "sci-a-1",
        subject: "science",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Gas plants absorb in photosynthesis?",
        options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
        correctAnswer: "Carbon dioxide",
        explanation: "Plants absorb CO₂ from the air.",
      },
      {
        id: "sci-a-2",
        subject: "science",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Example of food chain?",
        options: ["Grass → Rabbit → Fox", "Fox → Rabbit → Grass", "Rabbit → Grass → Fox", "Fox → Grass → Rabbit"],
        correctAnswer: "Grass → Rabbit → Fox",
        explanation: "Energy flows from producer to consumer.",
      },
      {
        id: "sci-a-3",
        subject: "science",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Function of mitochondria?",
        options: ["Control cell", "Produce energy", "Store water", "Protect cell"],
        correctAnswer: "Produce energy",
        explanation: "Mitochondria are the powerhouses of cells.",
      },
      {
        id: "sci-a-4",
        subject: "science",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "What causes seasons?",
        options: ["Distance from sun", "Earth's tilt", "Earth's rotation", "Moon's gravity"],
        correctAnswer: "Earth's tilt",
        explanation: "Earth's tilted axis causes seasons.",
      },
      {
        id: "sci-a-5",
        subject: "science",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Rock formed from cooled lava?",
        options: ["Sedimentary", "Metamorphic", "Igneous", "Limestone"],
        correctAnswer: "Igneous",
        explanation: "Igneous rocks form from cooled lava.",
      },
    ],
    expert: [
      {
        id: "sci-e-1",
        subject: "science",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Process releasing oxygen in photosynthesis?",
        options: ["Transpiration", "Respiration", "Photolysis", "Fermentation"],
        correctAnswer: "Photolysis",
        explanation: "Photolysis splits water, releasing oxygen.",
      },
      {
        id: "sci-e-2",
        subject: "science",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Characteristic of vertebrates?",
        options: ["No backbone", "Internal skeleton with backbone", "All carnivores", "Live only in water"],
        correctAnswer: "Internal skeleton with backbone",
        explanation: "Vertebrates have a backbone.",
      },
      {
        id: "sci-e-3",
        subject: "science",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Function of enzyme amylase?",
        options: ["Break down proteins", "Break down fats", "Break down starch", "Build muscle"],
        correctAnswer: "Break down starch",
        explanation: "Amylase breaks down starch into sugars.",
      },
      {
        id: "sci-e-4",
        subject: "science",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Role of nervous system?",
        options: ["Pump blood", "Digest food", "Transmit signals", "Produce hormones"],
        correctAnswer: "Transmit signals",
        explanation: "Nervous system transmits electrical signals.",
      },
      {
        id: "sci-e-5",
        subject: "science",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Water movement through soil?",
        options: ["Evaporation", "Infiltration", "Transpiration", "Precipitation"],
        correctAnswer: "Infiltration",
        explanation: "Infiltration is water soaking into soil.",
      },
    ],
  },

  reasoning: {
    foundation: [
      {
        id: "reas-f-1",
        subject: "reasoning",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Pattern: Circle, Square, Triangle, Circle, Square, ?",
        options: ["Circle", "Square", "Triangle", "Pentagon"],
        correctAnswer: "Triangle",
        explanation: "The pattern repeats: Circle, Square, Triangle.",
      },
      {
        id: "reas-f-2",
        subject: "reasoning",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Next number: 2, 4, 6, 8, ?",
        options: ["9", "10", "11", "12"],
        correctAnswer: "10",
        explanation: "Each number increases by 2.",
      },
      {
        id: "reas-f-3",
        subject: "reasoning",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Cat is to kitten as dog is to ?",
        options: ["Puppy", "Wolf", "Bark", "Paw"],
        correctAnswer: "Puppy",
        explanation: "A kitten is a young cat; a puppy is a young dog.",
      },
      {
        id: "reas-f-4",
        subject: "reasoning",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Odd one out: Apple, Banana, Carrot, Orange",
        options: ["Apple", "Banana", "Carrot", "Orange"],
        correctAnswer: "Carrot",
        explanation: "Carrot is a vegetable; others are fruits.",
      },
      {
        id: "reas-f-5",
        subject: "reasoning",
        level: "foundation",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "All dogs are animals. Rover is a dog. Rover is a ?",
        options: ["Dog", "Mammal", "Animal", "Pet"],
        correctAnswer: "Animal",
        explanation: "Logical deduction: dogs are animals.",
      },
    ],
    intermediate: [
      {
        id: "reas-i-1",
        subject: "reasoning",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Missing number: 3, 6, 12, 24, ?",
        options: ["36", "42", "48", "54"],
        correctAnswer: "48",
        explanation: "Each number is doubled.",
      },
      {
        id: "reas-i-2",
        subject: "reasoning",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Book is to read as fork is to ?",
        options: ["Eat", "Knife", "Metal", "Kitchen"],
        correctAnswer: "Eat",
        explanation: "Object to its primary use.",
      },
      {
        id: "reas-i-3",
        subject: "reasoning",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Which shape is different?",
        options: ["4-sided equal sides", "4-sided one shorter", "4-sided equal and right angles", "4-sided equal"],
        correctAnswer: "4-sided one shorter",
        explanation: "A square needs all equal sides AND right angles.",
      },
      {
        id: "reas-i-4",
        subject: "reasoning",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Most similar: Happy/sad, Big/large, Fast/slow, Hot/cold",
        options: ["Happy and sad", "Big and large", "Fast and slow", "Hot and cold"],
        correctAnswer: "Big and large",
        explanation: "'Big' and 'large' are synonyms.",
      },
      {
        id: "reas-i-5",
        subject: "reasoning",
        level: "intermediate",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "If A > B and B > C, which is true?",
        options: ["C > A", "A > C", "B > A", "C = A"],
        correctAnswer: "A > C",
        explanation: "Transitivity: A is greater than C.",
      },
    ],
    advanced: [
      {
        id: "reas-a-1",
        subject: "reasoning",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Missing number: 1, 4, 9, 16, 25, ?",
        options: ["30", "35", "36", "40"],
        correctAnswer: "36",
        explanation: "Perfect squares: 1², 2², 3², 4², 5², 6².",
      },
      {
        id: "reas-a-2",
        subject: "reasoning",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Painting is to artist as sculpture is to ?",
        options: ["Stone", "Chisel", "Sculptor", "Museum"],
        correctAnswer: "Sculptor",
        explanation: "Creation to creator relationship.",
      },
      {
        id: "reas-a-3",
        subject: "reasoning",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "NOT belonging: Pristine, Immaculate, Flawless, Damaged",
        options: ["Pristine", "Immaculate", "Flawless", "Damaged"],
        correctAnswer: "Damaged",
        explanation: "First three mean perfect; damaged is opposite.",
      },
      {
        id: "reas-a-4",
        subject: "reasoning",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Some students are athletes, some athletes are musicians. True?",
        options: ["All students are musicians", "Some students may be musicians", "No students are musicians", "All athletes are students"],
        correctAnswer: "Some students may be musicians",
        explanation: "Overlap allows some students to be musicians.",
      },
      {
        id: "reas-a-5",
        subject: "reasoning",
        level: "advanced",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Pattern: 2, 3, 5, 8, 13, ?",
        options: ["18", "20", "21", "24"],
        correctAnswer: "21",
        explanation: "Fibonacci: each is sum of previous two.",
      },
    ],
    expert: [
      {
        id: "reas-e-1",
        subject: "reasoning",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Next: 1, 1, 2, 3, 5, 8, 13, ?",
        options: ["19", "20", "21", "22"],
        correctAnswer: "21",
        explanation: "Fibonacci sequence.",
      },
      {
        id: "reas-e-2",
        subject: "reasoning",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Microscope is to small as telescope is to ?",
        options: ["Far", "Large", "Distant", "Sky"],
        correctAnswer: "Distant",
        explanation: "Tool to what it observes.",
      },
      {
        id: "reas-e-3",
        subject: "reasoning",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "All mammals are animals. All dogs are mammals. Therefore?",
        options: ["All animals are dogs", "All dogs are animals", "Some animals not dogs", "No dogs are animals"],
        correctAnswer: "All dogs are animals",
        explanation: "Logical transitivity.",
      },
      {
        id: "reas-e-4",
        subject: "reasoning",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "Same relationship as AUTHOR : BOOK?",
        options: ["Composer : Symphony", "Painter : Canvas", "Sculptor : Stone", "Architect : Blueprint"],
        correctAnswer: "Composer : Symphony",
        explanation: "Creator to creation.",
      },
      {
        id: "reas-e-5",
        subject: "reasoning",
        level: "expert",
        type: "multiple-choice",
        yearGroup: "year-3",
        question: "P implies Q, Q implies R, R is false. P is?",
        options: ["must be true", "must be false", "could be either", "undefined"],
        correctAnswer: "must be false",
        explanation: "Logical chain: if R false, then Q false, then P false.",
      },
    ],
  },
};

export function getRandomQuestions(
  subject: Subject,
  level: Level,
  count: number
): Question[] {
  const subjectQuestions = questionsDatabase[subject][level];
  const shuffled = [...subjectQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export function getQuestionsByLevel(subject: Subject, level: Level): Question[] {
  return questionsDatabase[subject][level];
}

export function getAllSubjects(): Subject[] {
  return ["english", "maths", "science", "reasoning"];
}
